run:
  timeout: 5m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable:
      - shadow
  gosec:
    excludes:
      - G101
      - G304
  revive:
    rules:
      - name: exported
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
  misspell:
    locale: US
  wrapcheck:
    ignoreSigs:
      - ".Errorf("
      - "apperror."
      - "errors.New("
      - "errors.As("
      - "errors.Is("
  gocritic:
    enabled-checks:
      - appendAssign
      - dupImport
      - evalOrder
      - initClause
      - rangeValCopy
      - sloppyLen
      - truncateCmp
      - unnecessaryBlock
      - boolExprSimplify
  linters:
    exclusions-rules:
      - path: "_test\\.go$"
        linters:
          - gosec
          - wrapcheck
      - path: "cmd/"
        linters:
          - wrapcheck

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - revive
    - gosec
    - bodyclose
    - contextcheck
    - copyloopvar
    - gocritic
    - gofmt
    - goimports
    - misspell
    - rowserrcheck
    - noctx
    - prealloc
    - wrapcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - gosec
        - wrapcheck
    - path: "cmd/"
      linters:
        - wrapcheck
